output "Acer Technologies VG271U 0x2091BB58" pos 0 0 transform 270
output "Acer Technologies VG271U TG0EE001854B" pos 1440 0
output eDP-1 pos 1440 1440

# Initial workspace for each output; other workspaces are created on demand.
workspace 1:1 output "Acer Technologies VG271U 0x2091BB58"
workspace 11:1 output "Acer Technologies VG271U TG0EE001854B"
workspace 21:1 output eDP-1
