ARG FEDORA_VERSION=44
ARG BASE_IMAGE=quay.io/fedora/fedora-bootc:${FEDORA_VERSION}

FROM ${BASE_IMAGE}

ARG SPACEOS_VERSION=0.0.0-devel
ARG SPACEOS_DISTRO_VERSION=0.0
ARG SPACEOS_BUILD_ID=local

RUN dnf5 install -y \
    anaconda \
    anaconda-install-img-deps \
    anaconda-dracut \
    dracut-config-generic \
    dracut-network \
    net-tools \
    squashfs-tools \
    xorrisofs \
    grub2-efi-x64-cdboot \
    plymouth \
    default-fonts-core-sans \
    default-fonts-other-sans \
    google-noto-sans-cjk-fonts \
    python3-mako \
    lorax-templates-* \
    biosdevname \
    prefixdevname \
    && dnf5 clean all

RUN mkdir -p /boot/efi \
    && cp -ra /usr/lib/efi/*/*/EFI /boot/efi

COPY installer-rootfs/ /
COPY assets/spaceos-logo.svg /usr/share/anaconda/pixmaps/spaceos-logo.svg

RUN printf '%s\n' \
        'NAME="SpaceOS Installer"' \
        "VERSION=\"${SPACEOS_VERSION}\"" \
        'ID=spaceos-installer' \
        'ID_LIKE=fedora' \
        "VERSION_ID=\"${SPACEOS_DISTRO_VERSION}\"" \
        "BUILD_ID=\"${SPACEOS_BUILD_ID}\"" \
        "PRETTY_NAME=\"SpaceOS ${SPACEOS_VERSION} Installer\"" \
        'HOME_URL="https://github.com/SpaceShaman/spaceos"' \
        'BUG_REPORT_URL="https://github.com/SpaceShaman/spaceos/issues"' \
        >/usr/lib/os-release \
    && ln -sfn ../usr/lib/os-release /etc/os-release

RUN mkdir -p /var/mnt
