FROM quay.io/fedora/fedora-bootc:44

ARG DISPLAYLINK_URL=https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v6.3.0-1/fedora-44-displaylink-1.15.0-1.github_evdi.x86_64.rpm
ARG DISPLAYLINK_SHA256=d29d4786267a12e91da50f1584e595093a6cbdeed2647f301a834d465f5d72c8

RUN dnf5 install -y --setopt=install_weak_deps=False \
      curl coreutils dkms kmod make gcc kernel-devel-matched \
    && curl --fail --location --silent --show-error "$DISPLAYLINK_URL" \
      --output /tmp/displaylink.rpm \
    && echo "$DISPLAYLINK_SHA256  /tmp/displaylink.rpm" | sha256sum --check --strict \
    && dnf5 install -y --setopt=install_weak_deps=False /tmp/displaylink.rpm \
    && rm -f /tmp/displaylink.rpm \
    && printf '%s\n' 'options evdi initial_device_count=4' \
      > /etc/modprobe.d/evdi.conf \
    && printf '%s\n' evdi > /etc/modules-load.d/evdi.conf

RUN set -eux; \
    kernel_version="$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}' kernel-core)"; \
    test -d "/usr/lib/modules/${kernel_version}"; \
    dkms install --force "evdi/1.15.0-1.github_evdi" -k "$kernel_version"; \
    depmod -a "$kernel_version"; \
    test -n "$(find "/usr/lib/modules/${kernel_version}" -type f -name 'evdi.ko*' -print -quit)"; \
    test -x /usr/libexec/displaylink/DisplayLinkManager; \
    test -f /usr/lib/systemd/system/displaylink-driver.service; \
    systemctl cat displaylink-driver.service | grep -F 'ExecStartPre=/sbin/modprobe evdi'; \
    systemctl cat displaylink-driver.service | grep -F 'ExecStart=/usr/libexec/displaylink/DisplayLinkManager'; \
    state="$(systemctl is-enabled displaylink-driver.service)"; \
    test "$state" = static || test "$state" = enabled; \
    ldd /usr/libexec/displaylink/DisplayLinkManager | tee /tmp/displaylink-ldd.txt; \
    ! grep -q 'not found' /tmp/displaylink-ldd.txt; \
    rm -f /tmp/displaylink-ldd.txt

RUN dnf5 clean all \
    && rm -rf /var/log/dnf5.log* /var/log/displaylink \
              /run/dnf /run/selinux-policy

RUN bootc container lint

CMD ["bash"]
