# Anaconda profile for the SpaceOS installation environment.

[Profile]
profile_id = spaceos
base_profile = fedora

[Profile Detection]
os_id = spaceos

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/spaceos.css
