font sans 8
default_border pixel 1
default_floating_border pixel 1
gaps inner 0
gaps outer 0

client.focused          $theme_fg $theme_bg $theme_fg $theme_fg $theme_fg
client.focused_inactive $theme_bg $theme_bg $theme_fg $theme_bg $theme_bg
client.unfocused        $theme_bg $theme_bg $theme_fg $theme_bg $theme_bg
client.urgent           $theme_accent $theme_bg $theme_accent $theme_accent $theme_accent
client.placeholder      $theme_bg $theme_bg $theme_fg $theme_bg $theme_bg

output * bg #000000 solid_color

bar {
    swaybar_command waybar
}
