# Ayu Dark
font sans 8
default_border pixel 1
default_floating_border pixel 1
gaps inner 0
gaps outer 0

client.focused          #B3B1AD #000000 #B3B1AD #B3B1AD #B3B1AD
client.focused_inactive #000000 #000000 #B3B1AD #000000 #000000
client.unfocused        #000000 #000000 #B3B1AD #000000 #000000
client.urgent           #F9AF4F #000000 #F9AF4F #F9AF4F #F9AF4F
client.placeholder      #000000 #000000 #B3B1AD #000000 #000000

output * bg #000000 solid_color

# Top bar: workspaces on the left, tray and system status on the right
bar {
    position top
    height 15
    font sans 10

    workspace_buttons yes
    binding_mode_indicator no
    separator_symbol " | "

    status_command /usr/libexec/spaceos-status

    tray_output *
    tray_padding 2

    colors {
        background         #000000
        statusline         #B3B1AD
        separator          #B3B1AD

        focused_workspace  #000000 #000000 #F9AF4F
        active_workspace   #000000 #000000 #B3B1AD
        inactive_workspace #000000 #000000 #B3B1AD
        urgent_workspace   #F9AF4F #F9AF4F #000000
    }
}

