# Ayu Light
font sans 8
default_border pixel 1
default_floating_border pixel 1
gaps inner 0
gaps outer 0

client.focused          #575F66 #FAFAFA #575F66 #575F66 #575F66
client.focused_inactive #FAFAFA #FAFAFA #575F66 #FAFAFA #FAFAFA
client.unfocused        #FAFAFA #FAFAFA #575F66 #FAFAFA #FAFAFA
client.urgent           #FF9940 #FAFAFA #FF9940 #FF9940 #FF9940
client.placeholder      #FAFAFA #FAFAFA #575F66 #FAFAFA #FAFAFA

output * bg #FAFAFA solid_color

# Top bar: workspaces on the left, tray and system status on the right
bar {
    position top
    height 15
    font sans 10

    workspace_buttons yes
    binding_mode_indicator no
    separator_symbol " | "

    status_command /usr/libexec/spaceos-status

    tray_output *
    tray_padding 2

    colors {
        background         #FAFAFA
        statusline         #575F66
        separator          #575F66

        focused_workspace  #FAFAFA #FAFAFA #FF9940
        active_workspace   #FAFAFA #FAFAFA #575F66
        inactive_workspace #FAFAFA #FAFAFA #575F66
        urgent_workspace   #FF9940 #FF9940 #FAFAFA
    }
}

