#!/usr/bin/bash
set -euo pipefail

if status=$(ostree admin status --json 2>/dev/null) \
    && jq --exit-status 'any(.deployments[]?; .staged == true)' <<<"$status" >/dev/null 2>&1; then
    printf '󰏗 Update is ready\nUpdate will be applied on next reboot\n'
fi
